IBM-Bluemix/docs

overview/index.md

Hi @jbetht  that / in front of (/glossary/index.html) was causing the url to render as https://www.ng.bluemix.net/docs/overview//glossary/index.html - it still works but lets remove it just to be safe. Please approve this change :|

Removed extra / in glossary related link

---

services/mobileaccess/google-auth-cordova.md

I'm not sure the reason, but I'm guessing it is a case issue on the link.  But if you try to go to the Google authentication iOS help from the Cordova help, you get a Page Not Found error.

link from Cordova docs to iOS doc didn't work

---

manageapps/secapps.md

The docs said using `using the OpenSSH command tool`. In fact, they refer to using the OpenSSL command line tool.

docs(secapps): change openssh reference to openssl

---

openwhisk/openwhisk_reference.md

Hello there!
I found and fixed a couple of typos in OpenWhisk Reference (available here: https://new-console.ng.bluemix.net/docs/openwhisk/openwhisk_reference.html).

OpenWhisk Reference typos

---

cli/index.md

Links to Bluemix CLI and CLI Plug-in Repository is broken when domain is not ng.bluemix.net
Modified these links to absolute links to ng.bluemix.net

Fixing broken links

---

openwhisk/openwhisk_mobile_sdk.md

typo use iOS instead of ios for the command wsk sdk install iOS
$ wsk sdk install ios
Unknown SDK component: ios
$ wsk sdk install iOS
Downloaded OpenWhisk iOS starter app. Unzip OpenWhiskIOSStarterApp.zip and open the project in Xcode.

typo use iOS instead of ios

---

pricing/index.md

@sefuhrer, please review and merge if you have no comments. The background of this change is in Usabilla defect 117688
https://jazzop27.rtp.raleigh.ibm.com:9443/ccm/web/projects/CloudOE#action=com.ibm.team.workitem.viewWorkItem&id=117688
Comment from that user is "This page referes to the Bluemix pricing calculator several times, but I can't find it."

Added location of pricing calculator

---

pricing/index.md

Adjustment to go to pricing page directly as an update to #136 ; additional editorial updates to refer to widgets on page as well.
@sefuhrer please review the change to see if you agree and merge if you do.
@April-yangzsh for your comment as well.

Edits for pricing calculators

---

runtimes/nl/zh/CN/liberty/customizingJRE.md

own lines in customizingJRE.md in zh/CN

``` surrounding codeblocks were appended to end of line and not on their

---

services/ObjectStorage/index.md

Most of the runtimes are now in the 'runtimes' directory instead of 'starters'.  Can you please push this to production once it is merged.

fix broken links to starters/*

---

manageapps/depapps.md

Not sure what happened but the link to the liberty runtime was still wrong.

change ../starters/liberty to../runtimes/liberty

---

homepage/nl/it/homepage.json

The value of ids in the homepage/homepage.json files must not be translated.
Please fix the translation and return the update in the next drop.
Or you can update the file in https://github.com/IBM-Bluemix/docs/blob/master/homepage/nl/ja/homepage.json
and create a pull request to refresh the doc site with the changes.

regarding TCT 160 and 200

---

dedicated/index.md

Bluemix Support had a request from Stack Overflow that the Bluemix docs not present Stack Overflow as the primary channel for Support. I have added the "official" Support messaging to the "Ask a question" section of this topic, and made a small change to the opening paragraph, to clarify the relationship between dW Answers, Stack Overflow, and the help ticket system.

Update "Getting Customer Support" to align with updated Support policy

---

starters/install_cli.md

Existing page continually states "Install the Bluemix CLI and the Cloud Foundry CLI"; but the Bluemix CLI is dependent on the CF CLI; it can't be installed without that dependency. We should put the links in the order in which people need to install.

Update with correct order of CLI installation

---

runtimes/ruby/index.md

Problem:
Link to Ruby on Rails Documentation broken
Solution:
Link should point to either the API docs or the guides.
The API docs link has been chosen here since the guides are more of learning resources than simple documentation.

Fix Rails documentation link

---

security/index.md

Corrected Bluemix Public and Dedicated relies on the network-within-a-network topology to rely, and other similar mismatches 
This list was wrong The following HTTP methods are allowed: DELETE GET HEAD OPTIONS POST PUT * TRACE HTTP inactivity times out at 2 minutes.

Edits to make plurals agree and correct a list

---

openwhisk/index.md

@sefuhrer this is not live yet, the plan to have the change in production later today.
Please review, but let's wait for @starpit to give confirmation that Bluemix production is updated with new CLI first.

openwhisk new cli available, deprecate python cli

---

cli/cliplug-in.md
cli/plugins/auto-scaling/index.md
cli/plugins/dev_mode/index.md

There isn't a domain-specific version of the CLI plugins repository, it is only available at plugins.ng.bluemix.net as per discussion on [slack](https://ibm-cloudplatform.slack.com/archives/feedback/p1469012465000068)
So (e.g.,) https://new-console.eu-gb.bluemix.net/docs/cli/cliplug-in.html contains a 404 link.

Fix Bluemix CLI Plugin Repository URLs

---

services/IoT/reference/mqtt/index.md

Fixed link to standards topic that is still draft. Replaced it with destination information until topic goes live.

Fixed link to missing content

---

develop/deploy_button.md

&excl; &lpar; &rpar; format correctly and don't cause CHKPII errors.

CHKPII: Use alternative character entities

---

services/ObjectStorage/os_security.md

Project_id is supposed to be before user_id. Which also makes more sense when talking scopes I believe.

Correct order of project_id and user_id

---

openwhisk/openwhisk_actions.md

@sefuhrer 
To be able to add "Packaging an action as a Node.js module" to TOC/Menu
and anchor is need this add the anchor.
TOC still needs to be done manually 
please review and merge
Fixes #845  partially

openwhisk: add anchor for package actions

---

admin/softlayerlink.md

Removed the credits section about the $200 when linking Bluemix and SoftLayer accounts.

Removed credits section

---

pricing/index.md

In the viewing credits section, removed the sentence about credit when linking Bluemix and SoftLayer accounts.

Updated viewing credits section

---

services/index.md

Please merge and request prod build. Key Protect will be removed on Dec 23rd.
See https://www.ibm.com/blogs/bluemix/2016/11/action-required-temporary-removal-ibm-key-protect-london-region/

Removed Key Protect London from regions table

---

services/index.md

Removed deprecated services from all regions: Service Discovery, Service Proxy
Today is the day of deprecation catalog removal in full. (4th Jan)

Removed deprecated services

---

services/IoT/applications/api.md

HTTP messaging APIs swagger doc was moved to a separate page, added a link to it.

Add link to http-messaging swagger doc

---

services/reqnsi.md

SD is deprecated and removed from catalog (4th Jan). Removed its entry in the services table.

Removed Service Proxy entry

---

runtimes/liberty/dynatrace.md
runtimes/liberty/environmentVariables.md
runtimes/liberty/nl/de/dynatrace.md
runtimes/liberty/nl/de/environmentVariables.md
runtimes/liberty/nl/es/dynatrace.md
runtimes/liberty/nl/es/environmentVariables.md
runtimes/liberty/nl/fr/dynatrace.md
runtimes/liberty/nl/fr/environmentVariables.md
runtimes/liberty/nl/it/dynatrace.md
runtimes/liberty/nl/it/environmentVariables.md
runtimes/liberty/nl/ja/dynatrace.md
runtimes/liberty/nl/ja/environmentVariables.md
runtimes/liberty/nl/ko/dynatrace.md
runtimes/liberty/nl/ko/environmentVariables.md
runtimes/liberty/nl/pt/BR/dynatrace.md
runtimes/liberty/nl/pt/BR/environmentVariables.md
runtimes/liberty/nl/zh/CN/dynatrace.md
runtimes/liberty/nl/zh/CN/environmentVariables.md
runtimes/liberty/nl/zh/TW/dynatrace.md
runtimes/liberty/nl/zh/TW/environmentVariables.md

As a result of PR [#317](https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/pull/317) on the websphere-liberty-buildpack, some renaming of classes has occurred (~Nov/2016).  After consultation with @jgawor, this PR updates Bluemix docs related to the config guidance for self-hosting of the Dynatrace Agent Jars.  Specifically, the environment variable **JBP_CONFIG_DYNATRACEAGENT** is no longer valid and should be replaced with **JBP_CONFIG_DYNATRACEAPPMONAGENT** to accommodate the liberty buildpack renaming changes.

Dynatrace agent name change

---

openwhisk/openwhisk_actions.md

This step is not longer need it since it got fixed int he CLI https://github.com/openwhisk/openwhisk/pull/1686
This change is not live, yet will merge once it's live

Update openwhisk_actions.md to remove extra step in docker sdk

---

openwhisk/openwhisk_actions.md
openwhisk/openwhisk_catalog.md

- Clarify nodejs zip actions, use can use index.js
- Update trigger limits definition for cloudant and alarm

openwhisk: docs sync 0130

---

cli/plugins/registry/index.md

Spotted while making other CLI edits; these links are not yet live. My mistake.

Removed 2 x links to topics not existing yet

---

cli/plugins/bluemix_admin/index.md

That plugin can't be installed from the current URL.

FIX bad URL for the BluemixAdmin plugin
