IBM-Bluemix/docs

README.md
@jenschlot  can you approve and merge these changes?
=> Suggested changes for Public users to fork/branch, pull

pricing/index.md
I happened to notice capitalization problems in a heading, an error in a UI label, a misused word, and missing "or region" following "country", which is an important legal issue.
=> Capitalization problems, UI label problem, legal

mobile/index.md
=> Merging changes for Mobile

troubleshoot/troubleshoot.md
@Crystal4545 , please review this change and merge if you agree. This rewording matches what we have in messages. Same change would need to be made in docs-staging.
=> Fix reference to support widget

cli/index.md
Please accept this pull request and request a push of the CLI plug-in to production.
=> Removed ICE from Downloads as it is deprecated

mobile/gettingstarted/cordova.md
Please validate changes and merge if looks OK.
=> Updating Cordova HelloWorld topic for production

services/mobileaccess/google-auth-ios.md
minor corrections to this help doc as I was going through it.
=> minor updates to google-auth-ios.md

services/DeliveryPipeline/index.md, services/TrackPlan/index.md
Details in WI 53328
https://hub.jazz.net/ccm09/resource/itemName/com.ibm.team.workitem.WorkItem/53328
=> Replaced T&P and DelPipeline dita with markdown

manageapps/secapps.md
See https://jazzop27.rtp.raleigh.ibm.com:9443/ccm/web/projects/CloudOE#action=com.ibm.team.workitem.viewWorkItem&id=88673
=> Fix Sydney IP address per support ticket 88673

security/index.md
@April-yangzsh , please review and merge.
=> Remove stray "x" per usabilla defect 106272

troubleshoot/index.md
I noticed this broken link in a troubleshooting topic. @Crystal4545 please review and merge. Also, can you please test the rest of the troubleshooting topics for broken links? Thanks.
=> Fix broken link

develop/bluemixlive.md
=> Live Sync updates to production

cfapps/starter_app_usage.md
Beth, please review and edit...
=> move cfapps/starter_app_usage to production

services/iotrtinsights/action_examples.md, services/iotrtinsights/actions.md, services/iotrtinsights/assets.md, services/iotrtinsights/dashboards.md, services/iotrtinsights/index.md, services/iotrtinsights/iotrtinsights_overview.md, services/iotrtinsights/iotrtinsights_task.md, services/iotrtinsights/prepare.md, services/iotrtinsights/rules.md, services/iotrtinsights/schemas.md, services/iotrtinsights/users.md
Added conrefs across all files.
Implemented new getting started templates.
=> Updates for IT10

services/nl/de/Auto-Scaling/index.md
=> Translation files for BM110ABD009_CD_DOC_Ship

openwhisk/openwhisk_triggers_rules.md
=> Correction to trigger rules

cli/index.md
Add Active Deploy to Bluemix plug-in table.
=> Add Active Deploy

homepage/homepage.json
Per the request of Tiona Fuller
=> Updated Mobile landing link and added Try link

develop/bluemixlive.md
Doc update from a forum post. Task 113428
=> Merging changes from staging to prod

services/index.md
Added "Application Security on Cloud" service to the Services by region table
=> Added 'Application Security on Cloud' service

services/IotDriverInsights/index.md, services/IotDriverInsights/iotdriverinsights_admin.md, services/IotDriverInsights/iotdriverinsights_overview.md, services/IotMapInsights/index.md, services/IotMapInsights/iotmapinsights_admin.md, services/IotMapInsights/iotmapinsights_overview.md
Please validate changes and merge if everything looks OK!
=> Add copyright and year

services/mobilepush/c_advance_notifications.md, services/mobilepush/c_overview_push.md, services/mobilepush/index.md, services/mobilepush/t_manage_tags.md, services/mobilepush/t_push_provider_android.md, services/mobilepush/t_push_provider_ios.md, services/mobilepush/t_restapi.md
=> updated push files

services/mobilepush/c_android_enable.md, services/mobilepush/c_cordova_enable.md, services/mobilepush/c_ios_enable.md, services/mobilepush/c_tag_basednotifications.md, services/mobilepush/t_push_provider_ios.md, services/mobilepush/t_restapi.md
=> fix bad links

openwhisk/openwhisk_catalog.md
=> Document that alarms fire in UTC

openwhisk/openwhisk_packages.md
typo sample instead of custom for sharing a custom package
=> typo sample instead of custom

mobile/gettingstarted/cordova.md
Please validate changes and merge if everything looks good.
=> cordova cord update for prod

services/mobilepush/t_advance_badge_sound_payload.md, services/mobilepush/t_android_receive.md, services/mobilepush/t_android_register.md, services/mobilepush/t_cordova_install.md, services/mobilepush/t_enable-ios-notifications-receive.md, services/mobilepush/t_enable_ios_notifications_install.md, services/mobilepush/t_enable_ios_notifications_register.md, services/mobilepush/t_get_tags.md, services/mobilepush/t_handle_actionable_notifications_ios.md, services/mobilepush/t_holding_notifications_android.md, services/mobilepush/t_manage_tags.md, services/mobilepush/t_push_provider_android.md, services/mobilepush/t_push_provider_ios.md, services/mobilepush/t_push_tagsmain.md, services/mobilepush/t_restapi.md, services/mobilepush/t_sandbox.md, services/mobilepush/t_send_push_notifications.md, services/mobilepush/t_service_instance.md, services/mobilepush/t_subscribe_tags.md, services/mobilepush/t_use_tags.md, services/mobilepush/troubleshooting.md
=> new change set

services/nl/it/iotrtinsights/images/iota.svg
Italian iota.svg file returned. All rtinsights files now committed.
=> Adding iota svg file

services/mobileaccess/protecting-resources-java.md
merging myself after checking with Eric Koeck
=> fix link to runtimes/liberty

services/DeliveryPipeline/index.md
Fixing UI labels from tech review.
=> Updating pipeline docs from staging.

runtimes/nodejs/index.md, runtimes/nodejs/updates.md
=> switch nodejs back to version3.3 doc until the v3.4 buildpack is in

openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md
=> Remove 'response:' prefix from blocking action activation response.

openwhisk/openwhisk_reference.md
The npm package gm for GraphicsMagick is available for OpenWhisk
=> Add npm pacakge gm for openwhisk

openwhisk/index.md, openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_mobile_sdk.md, openwhisk/openwhisk_packages.md, openwhisk/openwhisk_reference.md
@sefuhrer please merge when you have a chance.
Fixes #264 #273 #275 #283
=> Ready: sync docs with openwhisk

openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_reference.md
=> sync openwhisk docs speechtotext and catalog

runtimes/python/index.md
Update the example from Python 3.4 to Python 3.5
=> Clarify support for both Python 2 and Python 3

services/IotMapInsights/index.md, services/IotMapInsights/iotmapinsights_admin.md, services/IotMapInsights/iotmapinsights_overview.md
ID edits and styling for the republish to production to fix the navigation issue in the new doc app.
=> Mpurcell merging iotmapinsight changes from staging

openwhisk/openwhisk_catalog.md
=> openwhisk add pushnotifications docs

openwhisk/index.md, openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_mobile_sdk.md, openwhisk/openwhisk_reference.md, openwhisk/openwhisk_triggers_rules.md
@sefuhrer please merge when you have chance
=> series of updates for openwhisk docs

services/IoTAutomotive/index.md
Added 2 new related links as per dev request.
Also fixed the Bluemix Catalog link
=> Added new content and a fix

services/IotInsurance/index.md
=> Adding link to experimental catalog

starters/deploy_vs.md
=> commit dotnet doc,  deploy_vs which will be linked to from the ace

services/IotElectronics/index.md
=> Revert "correcting relative link that didn't resolve"

services/mobileaccess/advanced-topics-oauthsdk.md, services/mobileaccess/advanced-topics-touchid.md, services/mobileaccess/custom-auth-android.md, services/mobileaccess/custom-auth-config-mca.md, services/mobileaccess/custom-auth-cordova.md, services/mobileaccess/custom-auth.md, services/mobileaccess/facebook-auth-ios-swift-sdk.md, services/mobileaccess/facebook-auth-overview.md, services/mobileaccess/facebook-auth-web.md, services/mobileaccess/getting-started-android.md, services/mobileaccess/getting-started-cordova.md, services/mobileaccess/getting-started-ios-swift-sdk.md, services/mobileaccess/getting-started-ios.md, services/mobileaccess/getting-started.md, services/mobileaccess/google-auth-android.md, services/mobileaccess/google-auth-ios-swift-sdk.md, services/mobileaccess/google-auth-overview.md, services/mobileaccess/google-auth-web.md, services/mobileaccess/index.md, services/mobileaccess/overview.md, services/mobileaccess/protecting-resources-java.md, services/mobileaccess/protecting-resources-local.md, services/mobileaccess/protecting-resources-nodejs.md, services/mobileaccess/protecting-resources.md, services/mobileaccess/sdks-samples-apis.md
plus various editing corrections.
=> added Help topic, corrections to web topics

manageapps/workingWithProxy.md, runtimes/liberty/offlineMode.md, runtimes/liberty/topics.md, runtimes/liberty/updates.md, runtimes/nodejs/index.md, runtimes/nodejs/offlineMode.md, runtimes/nodejs/updates.md
=> latest updates for new node and liberty versions plus offline mode &

public/index.md
Added missing word region to a sentence. Corrected backend to back-end.
=> Minor edits to index.md

services/blockchain/etn_sdk.md
Correct hlc->hfc in example code
=> hlc -> hfc

admin/profile.md
=> Update profile.md for IBMid

admin/softlayerlink.md
=> Update softlayerlink.md for IBMid

cfapps/ee.md
=> Update ee.md for IBMid

cli/reference/cfcommands/index.md
=> Update index.md for IBMid

services/mobilepush/c_user_basednotifications.md
=> Merging updated Push topic

services/mobilepush/t_manage_user.md
=> adding t_manage_user

services/BlockStorage/blockstorage_about.md, services/BlockStorage/blockstorage_attachingvolume.md, services/BlockStorage/blockstorage_creatingvolume.md, services/BlockStorage/blockstorage_preparingvolume.md, services/BlockStorage/index.md
=> Moving latest updates from staging to docs

services/mobileaccess/custom-auth-android.md, services/mobileaccess/facebook-auth-android.md, services/mobileaccess/facebook-auth-ios-swift-sdk.md, services/mobileaccess/getting-started-android.md, services/mobileaccess/getting-started-ios-swift-sdk.md, services/mobileaccess/google-auth-android.md, services/mobileaccess/google-auth-ios-swift-sdk.md
includes bold added to some UI elements
=> added-mcaAuthorizationmanager-line-and-formatting

services/blockchain/etn_sdk.md
Added some lessons from IBM-Blockchain/ibm-blockchain-issues#8 on connecting the bluemix service to the sdk.
=> Some clarifications on using the SDK with blockchain bluemix service

services/BlockStorage/ts_index.md
This is only a draft and meant for staging.
=> Adding new troubleshooting  topic

services/IoTAutomotive/index.md, services/IoTAutomotive/iotautomotive_admin.md, services/IoTAutomotive/iotautomotive_overview.md, services/IotDriverInsights/drb_index.md, services/IotDriverInsights/drb_iotdriverinsights_admin.md, services/IotDriverInsights/drb_iotdriverinsights_overview.md, services/IotDriverInsights/index.md, services/IotDriverInsights/tp_index.md, services/IotDriverInsights/tp_iotdriverinsights_admin.md, services/IotDriverInsights/tp_iotdriverinsights_overview.md, services/IotMapInsights/index.md, services/IotMapInsights/iotmapinsights_admin.md, services/IotMapInsights/iotmapinsights_overview.md
IBMid changes
Added table titles
Added 3 links to Driver Behavior Resources page
=> Pushing minor doc updates to production for refresh

services/index.md
Added Block Storage and reflected that it is hosted in London only.
=> Added Block Storage service row

admin/adminpublic.md
Replaced the Support and Account icon with Avatar
=> Update adminpublic.md for Avatar icon

admin/softlayerlink.md
=> Update softlayerlink.md for Avatar

admin/account.md
=> Update account.md for Avatar

admin/profile.md
=> Update profile.md for Avatar

admin/users_roles.md
=> Update users_roles.md for Avatar

admin/orgs_spaces.md
=> Update orgs_spaces.md for Avatar icon

pricing/index.md
=> Update index.md for Avatar

cfapps/ee.md
=> Update ee.md for Avatar

services/mobilepush/c_android_enable.md, services/mobilepush/c_enable_push.md, services/mobilepush/c_overview_push.md, services/mobilepush/c_user_basednotifications.md, services/mobilepush/index.md, services/mobilepush/t__main_push_config_provider.md, services/mobilepush/t_manage_tags.md, services/mobilepush/t_manage_user.md, services/mobilepush/t_push_provider_android.md, services/mobilepush/t_restapi.md
=> Push Notifications updates -25Aug

openwhisk/index.md, openwhisk/openwhisk_about.md, openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_mobile_sdk.md, openwhisk/openwhisk_reference.md, openwhisk/openwhisk_triggers_rules.md
@sefuhrer please review and merge.
=> sync openwhisk docs for 0826

runtimes/liberty/autoConfig.md, runtimes/liberty/buildpackDefaults.md, runtimes/liberty/dynatrace.md, runtimes/liberty/environmentVariables.md, runtimes/liberty/index.md, runtimes/liberty/jconsole.md, runtimes/liberty/libertyFeatures.md, runtimes/liberty/loggingAndTracing.md, runtimes/liberty/memoryLimits.md, runtimes/liberty/newRelic.md, runtimes/liberty/offlineMode.md, runtimes/liberty/optionsForPushing.md, runtimes/liberty/oracle_jre.md, runtimes/liberty/topics.md, runtimes/liberty/updates.md, runtimes/liberty/usingBetaFeatures.md
latest liberty version updates
=> changes for latest liberty version

services/mobilefoundation/c_using_mfs_p1.md, services/mobilefoundation/c_using_mfs_p2.md
Hide analytics server related doc till service is updated
=> hide analytics related documentation

pricing/index.md
Removed references to SQL DB as the service has been deprecated
=> Removed SQL DB reference

openwhisk/index.md, openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_feeds.md, openwhisk/openwhisk_reference.md
Hi @sefuhrer please review and merge.
Please note that in this drop I added a new document openwhisk_feeds.md
=> set of changes to sync openwhisk 0908

openwhisk/index.md
=> add beta to openwhisk main title

pricing/index.md
Added a supported currency table.
=> Update index.md for supported currencies

services/IoT/add_users.md, services/IoT/cloudant_connector.md, services/IoT/devices/device_mgmt/index.md, services/IoT/devices/device_mgmt/requests.md, services/IoT/gateways/java.md, services/IoT/iotplatform_task.md, services/IoT/nodereddevice_sample.md, services/IoT/reference/device_model.md, services/IoT/reference/extensions/index.md
Accessibility and other ID edits for Watson IoT Platform docs as listed in https://github.ibm.com/Watson-IoT/Docs/issues/315.
=> 091316  mid sprint 75 to production (ii) #315

services/IoT/devices/libraries/nodejs.md, services/IoT/gateways/mqtt.md
=> 091316 mid sprint 75 to production (ii) #315 

services/index.md
Key Protect now available in US South
=> Updated regions table to include Key Protect US South

develop/bluemixlive.md
Changed "IBM id" references to "IBMid".
=> Update bluemixlive.md for IBMid

services/iotrtinsights/prepare.md
Changed one "IBM IDs" reference to "IBMids".
=> Update prepare.md for IBMid

services/iotrtinsights/users.md
Changed one reference of "IBM ID" to "IBMid".
=> Update users.md for IBMid

openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_packages.md, openwhisk/openwhisk_reference.md, openwhisk/openwhisk_triggers_rules.md
@sefuhrer please take into account some spaces in certain actions.md
I added 2 spaces in some empty lines to allow the numbering in markdown to work properly
currently we have a number 1, 1 instead of 1,2 in calling external API section
=> openwhisk_docs_0921

develop/deploy_button.md
Replace:
&#33; with !
&#40; with (
&#41; with )
Unmatched (I /I) tag on/after TRN line: 174
Unmatched (STRONG /STRONG) tag on/after TRN line: 189
=> CHKPII: Incorrect hex symbols and markup

services/ComposeForElasticsearch/index.md, services/ComposeForEtcd/index.md, services/ComposeForMongoDB/index.md, services/ComposeForPostgreSQL/index.md, services/ComposeForRabbitMQ/index.md, services/ComposeForRedis/index.md, services/ComposeForRethinkDB/index.md
These are the ComposeForDB production documents in a single PR.
=> Compose prod

services/mobilepush/c_android_enable.md, services/mobilepush/c_chrome_firefox_enable.md, services/mobilepush/c_cordova_enable.md, services/mobilepush/c_ios_enable.md, services/mobilepush/index.md, services/mobilepush/t_manage_tags.md, services/mobilepush/t_manage_user.md, services/mobilepush/t_push_provider_android.md
Cordova confir related roll back, code snippet corrections.
=> Updates for #568, #659, #607, #550

services/mobileaccess/index.md
actually I already committed this change by mistake. I made a minor change in order to make a formal pull request. It is a very small change.
=> Update index.md getting started

cfapps/byob.md
=> CHKPII: Use alternative symbol

services/mobilepush/c_android_enable.md, services/mobilepush/c_overview_push.md, services/mobilepush/c_user_basednotifications.md, services/mobilepush/t_push_provider_android.md
Editorial and snippet corrections, in addition to clientSecret updates.
=> New editorial and code snippet corrections

openwhisk/openwhisk_actions.md, openwhisk/openwhisk_reference.md
please review and merge @sefuhrer
=> fix some link references for openwhisk

openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_mobile_sdk.md, openwhisk/openwhisk_packages.md, openwhisk/openwhisk_reference.md, openwhisk/openwhisk_triggers_rules.md
=> Openwhisk docs sync 10 06

services/Auto-Scaling/index.md
Updated policy configuration part.
Another hints for the wrong metric list
=> Update index.md to fix the metric support #2

cli/plugins/bluemix_admin/index.md
call out the admin cli plugin is for bluemix dedicated/local only, not for public
=> update index.md for admin cli

services/mobilepush/c_android_enable.md, services/mobilepush/c_chrome_firefox_enable.md, services/mobilepush/c_cordova_enable.md, services/mobilepush/c_ios_enable.md, services/mobilepush/c_overview_push.md, services/mobilepush/index.md, services/mobilepush/interactive_notifications.md, services/mobilepush/next_steps_tags.md, services/mobilepush/t_advance_badge_sound_payload.md, services/mobilepush/t_android_create_unbound_service.md, services/mobilepush/t_manage_tags.md, services/mobilepush/t_push_provider_android.md, services/mobilepush/t_push_provider_ios.md, services/mobilepush/t_restapi.md
Code snippet corrections, GCM to FCM updates, and Advanced Push notification link corrections.
=> link correction, FCM related updates

services/mobilefoundation/c_using_mfs_p1.md, services/mobilefoundation/c_using_mfs_p3.md, services/mobilefoundation/c_using_mfs_p4.md, services/mobilefoundation/customdomainconfig.md, services/mobilefoundation/index.md, services/mobilefoundation/maint_updates.md, services/mobilefoundation/mdoverview.md
Also update to last update field in md.
=> Documentation for 2 new plans

openwhisk/openwhisk_actions.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_reference.md
@sefuhrer please review and merge.
Hope this time the DomainName problems is solved.
=> Minor updates for openwhisk docs 10_19

admin/users_roles.md
Added the removing team members topic to users_roles. 
Updates for 24th October.
=> Added new topic to users_roles

admin/orgs_spaces.md
=> Updated orgs_spaces.md for Oct changes

admin/account.md
Updated for 24 Oct changes.
Updated relative links - #662.
=> Updated account.md for Oct changes

icons/icon_remove_teamuser.svg
Added the remove teamuser icon.
=> New remove teamuser icon

admin/users_roles.md
Updated the reference in users_roles.md to reflect the new icon name.
=> Updated remove icon in users_roles.md

admin/users_roles.md
Last updated moved back to H1.
=> Updated users_roles to revert last updated

admin/orgs_spaces.md
Moved last updated back to H1.
=> Updated orgs_spaces.md for last updated

admin/account.md
Moved last updated back to H1.
=> Updated account.md for last updated

admin/profile.md
=> Updated profile.md for oct changes

admin/softlayerlink.md
=> Updated softlayerlink.md for oct delivery

admin/images/BluemixSoftLayerBill.svg
Updated image to reflect the 24 Oct changes.
=> Updated graphic for billing

pricing/index.md
=> Updated index.md for oct delivery

pricing/index.md
Update to pricing page link to new version
=> Update pricing page link

cfapps/index.md
They were written in pain text
=> Corrected Bluemix conrefs

cfapps/starter_app_usage.md
Bluemix was written in plain text
=> Added bluemix conref

cli/index.md
Remove OpenStack CLI and Virtual Server references in this paragraph. Thank you.
=> Remove a couple references in this paragraph

services/BlockStorage/blockstorage_about.md, services/BlockStorage/blockstorage_attachingvolume.md, services/BlockStorage/blockstorage_creatingvolume.md, services/BlockStorage/blockstorage_preparingvolume.md, services/BlockStorage/blockstorage_usingsnapshot.md, services/BlockStorage/blockstorage_usingvolume.md, services/BlockStorage/index.md, services/BlockStorage/ts_index.md
Update prod files for the WoW announcements.
=> Moving staging files to prod

openwhisk/openwhisk_reference.md
@sefuhrer please review and merge, this is already deployed to production
=> update openwhisk limits

services/IoTAutomotive/index.md, services/IoTAutomotive/iotautomotive_admin.md, services/IoTAutomotive/iotautomotive_overview.md, services/IotDriverInsights/drb_iotdriverinsights_overview.md, services/IotMapInsights/iotmapinsights_overview.md
as per new Bluemix doc framework process for handling "last updated by".
=> More updates to add the new lastupdated code

openwhisk/openwhisk_actions.md
=> added js zip actions for openwhisk

openwhisk/openwhisk_reference.md
=> OpenWhisk Reference Typo

admin/softlayerlink.md
Changed the title, added topicrefs, added new upgrade details.
=> Added upgrade details to softlayerlink.md for

services/mobileaccess/custom-auth-cordova.md, services/mobileaccess/facebook-auth-cordova.md, services/mobileaccess/getting-started-cordova.md, services/mobileaccess/google-auth-cordova.md
Cordova updates for https://github.ibm.com/bluemix-mobile-services/bmd-project-codegen/issues/172
=> Cordova updates for bmd-project-codegen/issues/172

services/mobilefoundation/c_using_mfs_p1.md, services/mobilefoundation/c_using_mfs_p2.md, services/mobilefoundation/c_using_mfs_p3.md, services/mobilefoundation/c_using_mfs_p4.md, services/mobilefoundation/customdomainconfig.md, services/mobilefoundation/index.md, services/mobilefoundation/maint_updates.md, services/mobilefoundation/mdoverview.md
additionally changes for lastupdated header
=> Remove new-console changes

openwhisk/openwhisk_actions.md
@sefuhrer please review. This supersede #665 but it acknowledge @krook contribution
=> Reword Docker instructions slightly.

openwhisk/index.md, openwhisk/openwhisk_actions.md
* added java action docs
* added cli docs for passing params via file
* made sequence section higher level
* minor typos
Also Fixes #771
We need the menu changes:
To show sequence at a high level outside javascript actions
To show java actions at the same level of other type of action like javascript, python, etc...
=> Few docs updates for openwhisk

admin/account.md
=> Moved last updated

admin/account.md
Accessibility updates - removed italics from table
=> Removed italics from table

admin/orgs_spaces.md
Updated relative path links - #662
=> Updated relative links

admin/users_roles.md
Accessibility updates to remove italics from tables
Updated relative path link - #662
=> Removed italics from tables

pricing/index.md
Accessibility updates to remove italics from tables and figures
=> Removed italics from tables and figures

services/mobileaccess/getting-started-cordova.md
changed info about Android version support since Cordova supports only up to 23.
=> adding Nana's latest changes

services/mobilefoundation/index.md
110695 - add known limitation [GVT issue]
=> 110695 - add known limitation [GVT issue]

cli/plugins/bluemix_admin/index.md
=> Change organisation to permission

admin/softlayerlink.md
Updated for clarification following the TCT #292 query.
=> Updated following TCT #292

openwhisk/openwhisk_triggers_rules.md
=> openwhisk actions in package can be in rules

openwhisk/openwhisk_catalog.md
=> openwhisk: update cron field info to 5 fields

openwhisk/index.md
@sefuhrer please review.
The wording might need some refinement.
Fixes #843
=> openwhisk: update getting started reference UI editor

admin/profile.md
Updated the icon paths as the icons are not displaying correctly.
=> Updated icon paths

admin/users_roles.md
Updated the icon path as the remove icon is not displaying properly.
=> Updated icon path

runtimes/liberty/dynatrace.md, runtimes/liberty/libertyFeatures.md, runtimes/liberty/optionsForPushing.md, runtimes/liberty/ts_index.md, runtimes/liberty/updates.md
fixed dynatrace bad formatting
=> latest updates for liberty 3.5,  added liberty troubleshooting doc,

admin/softlayerlink.md
New paragraph describing how subscription account can access infrastructure resources.
=> Added subscription paragraph

openwhisk/openwhisk_catalog.md
=> openwhisk: update watson docs for new packages

overview/whatisbluemix.md
https://github.ibm.com/Bluemix/docs/issues/295
=> Change Table caption

admin/orgs_spaces.md
Updated managing quota for #177
=> Updated managing quota

pricing/index.md
Accessibility updates for table titles #295
=> Updated table titles - #295

services/IoTAutomotive/index.md, services/IoTAutomotive/iotautomotive_apis.md
Removed 2 obsolete line items from table as per dev request. Also other
minor ID edits for clarity.
=> Minor content updates

manageapps/app_mng.md, runtimes/liberty/ts_index.md
=> updates for noproxy utility in manageapps,  fix for typo in

services/mobileaccess/getting-started-cordova.md
as discussed with Tiona awhile ago. linked to topic about latest Android version supported by Cordova
=> adding link to get latest Android version

services/mobileaccess/getting-started-cordova.md
last correction introduced new renumbering error, corrected.
=> corrected renumbering error

openwhisk/openwhisk_actions.md, openwhisk/openwhisk_apigateway.md, openwhisk/openwhisk_catalog.md, openwhisk/openwhisk_feeds.md, openwhisk/openwhisk_packages.md, openwhisk/openwhisk_reference.md
- adds apigateway swagger file config
- adds info on openwhisk npm package
- minor formatting and typos.
=> openwhisk updates for 01/04

services/mobileaccess/index.md, services/mobileaccess/sdks-samples-apis.md
=> Jsinger removed api links

admin/softlayerlink.md
=> Remove reference to Service Discovery (deprecated)

openwhisk/openwhisk_reference.md
Remove digit from sentence following advice from Carlos Santana.
Fixing in time for Jan 19 translation drop.
=> Translation query correction

admin/index.md
1) add minValue query parameter for Application endpoints
2) update data format for Environment metrics - cpu, memory, and disk
=> Update Metrics Documentation

icons/Lite.svg
New Lite tag graphic for Freemium Beta #886
=> Lite tag for Beta topic

pricing/standard_account.md
New Standard Account Beta topic for Freemium Beta #886
=> New standard account beta topic

pricing/standard_account.md
Janhavi has requested the removal of the third service.
=> Removed third service

services/IoT/reference/security/RM_security.md
=> Fixed last updated by tag

security/images/security_local_platform.ai
The doc uses the .svg, not the .ai, and the text can't be extracted from this ai, so causes a translation error.
=> Delete file  to resolve tranlsation problem

services/IoT/nl/zh/CN/devices/api.md, services/IoT/nl/zh/TW/applications/api.md, services/IoT/nl/zh/TW/devices/api.md
Same issue as https://github.com/IBM-Bluemix/docs/pull/1108/files  found in the devices topic also.
=> Fixed bad URL in zh_CN topic after translation

monitor_log/logging/kibana3/logging_kibana_query.md
Do this to resolve CHKPII errors
=> Remove comments

troubleshoot/troubleshoot.md
https://github.ibm.com/Bluemix/docs/issues/1161
=> Updates for 1161

services/HistoricalInstrumentAnalytics/index.md, services/HistoricalInstrumentAnalytics/toc, services/InstrumentAnalytics/index.md, services/InstrumentAnalytics/toc, services/SimulatedHistoricalInstrumentAnalytics/index.md, services/SimulatedHistoricalInstrumentAnalytics/toc, services/SimulatedInstrumentAnalytics/index.md, services/SimulatedInstrumentAnalytics/toc
Based off of docs-staging except with updated dates (today) and production URLs and toc in production format
=> WF-48 - initial commit for 4 new bluemix services

cli/plugins/registry/index.md
Required for Registry production push on 27th Feb. 1st pass for technical review, as this has had all non-production features removed.
=> Create: registry CLI index.md - Push when Container Service goes for Armada Beta.

references/accessibility_features.md
Take dashes out of commented out table
=> Fix CHKPII error

services/mobileaccess/facebook-auth-cordova.md
Fixing this English will also help fix TCT query #470 https://www-607.ibm.com/software/globalization/translationcommunications/BaseServlet.wss?taskName=ReadArticlePre&arrefnum=7701915770&prrefnum=2000006467
=> Link title has changed

cli/plugins/registry/index.md
Spotted by Kristin, should fix these problems.
=> Fix duplicate entries, alphabetize entries

services/IoTAutomotive/index.md, services/IoTAutomotive/iotautomotive_apis.md, services/IotDriverInsights/drb_index.md, services/IotDriverInsights/drb_iotdriverinsights_admin.md, services/IotDriverInsights/index.md, services/IotDriverInsights/tp_index.md, services/IotMapInsights/index.md, services/IotMapInsights/iotmapinsights_overview.md
added no toc to #rellinks instances
=> Fixed Related Link issue in TOC

services/IoTAutomotive/toc, services/IotDriverInsights/toc, services/IotMapInsights/toc
Config for the new nav changes as tested on staging. Ready for tomorrow's big push!
=> Update the existing ToC to the new NAV toc

services/IoT/applications/libraries/python.md, services/IoT/blockchain/dev_blockchain.md, services/IoT/devices/device_dev_index.md, services/IoT/index.md, services/IoT/iot_platform_client_lib.md, services/IoT/platform_authorization.md, services/IoT/reference/security/connect_devices_apps_gw.md, services/IoT/toc
https://github.ibm.com/Watson-IoT/Docs/issues/600
=> IoT new nav  deployment issue #600

admin/orgs_spaces.md
=> Updated quota definition

cli/plugins/registry/index.md
... Though the dd tags don't seem to allow code formatting for Markdown, which makes it difficult to read :/
=> Specified format for Bluemix path

services/IoT/getting_started/getting-started-iot-nodered.md
New topic to be exposed externally with no nav updates.
=> Dark release of updated IoT Platform starter topic

admin/orgs_spaces.md
Tweak over my other tweak - added BX to the command and used the option the BX CLI uses (BX likes to reverse the command pattern - don't ask me why as it is confusing).  
bx iam org-delete
cf delete-org
(but only the bx iam org-delete option works for this task).
=> Correct fix (syntax)

openwhisk/openwhisk_pushnotifications.md
=> openwhisk: update pushnotifications docs

cloudnative/tutorial_bff.md
Added steps to view swapper and explore APIs.
=> Update tutorial_bff.md to identity swagger URLs 

services/DevOpsInsights/index.md, services/DevOpsInsights/insights_developer.md, services/DevOpsInsights/insights_risk.md, services/DevOpsInsights/insights_team.md, services/DevOpsInsights/jenkins_pipeline.md, services/DevOpsInsights/risk_jenkins.md, services/DevOpsInsights/risk_policies.md, services/DevOpsInsights/toc
-TOC link fixed
-Accessibility tweaks to existing content
-Plugin instructions updated
-Experimental tag removed
=> Various Insights updates

runtimes/liberty/loggingAndTracing.md, services/ContinuousDelivery/upgrade_projects.md
Add section for "Diego: change tracing configuration via SSH"
=> Add section for "Diego: change tracing configuration via SSH"

pricing/estimating_costs.md
The scenario now contains the example.
=> Removed example

services/conversation/show-me.md
=> Update from staging

services/IotInsurance/iotinsurance_wally_integration.md
Because Dragos told us to.
(He says Hi Janice!)
=> Updated WALLY_SECURITY_TOKEN to WALLY_TOKEN.

services/IoT/toc
and removed the draft topic of im_index_split
=> Adding RM Beta features

services/IoT/devices/device_cmd_api.md
Fix copyright header information
=> Fix for #716 push
